version: '3.8'

services:
  # Base de datos MongoDB para desarrollo
  mongodb:
    image: mongo:6.0
    container_name: clinica_mongodb_dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: clinica_veterinaria_dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - clinica_dev_network

  # API REST para desarrollo
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: clinica_api_dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB=mongodb://admin:password123@mongodb:27017/clinica_veterinaria_dev?authSource=admin
      - JWT_SECRET=mi_secreto_jwt_super_seguro_2024_clinica_veterinaria_dev
      - JWT_EXPIRE=24h
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - clinica_dev_network
    volumes:
      - ./logs:/app/logs
      - ./app:/app/app
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    command: npm run dev

volumes:
  mongodb_dev_data:
    driver: local

networks:
  clinica_dev_network:
    driver: bridge 